apiVersion: v1 
kind: ConfigMap
metadata:
  name: my-var
data:
  pass: "redhat"
  user: "linux"
  db: "studentapp"

---
    metadata:
      labels:
        app: xyz-app
    spec:
      containers:
        - name: my-container
          image: mysql
          ports:
            - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: redhat