apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: studentapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: studentapp
  template:
    metadata:
      labels:
        app: cbz-app
    spec:
      containers:
        - name: my-container
          image: nginx
          ports:
            - containerPort: 80 

        - name: tomcat-container
          image: tomcat
          ports: 
            - containerPort: 8080      