apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: studentapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentapp
  template:
    metadata:
      labels:
        app: studentapp
    spec:
      containers:
        - name: my-container
          image: nginx
          ports:
            - containerPort: 80 
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 300m
              memory: 2Gi
  strategy:
    type: RollingUpdate
