## POD1
apiVersion: v1
kind: Pod
metadata:
  name: home-app
  labels:
    app: home-app
spec:
  containers:
    - name: home-app
      image: nginx
      ports:
        - containerPort: 80

---
## POD2
apiVersion: v1
kind: Pod
metadata:
  name: laptop-app
  labels:
    app: laptop-app
spec:
  containers:
    - name: laptop-app
      image: httpd
      ports:
        - containerPort: 80

---
apiVersion:
